USE [master]
GO

/****** Object:  Database [BD]    Script Date: 17.12.2017 17:36:59 ******/
CREATE DATABASE [BD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BD_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD] SET  MULTI_USER 
GO

ALTER DATABASE [BD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD] SET  READ_WRITE 
GO


